Support for Server Tokens
melkortf/tf2-servers pull request #156
Opened 2024-07-21 20:14 UTC by joshuafhiggins

Users would be able to specify a game server token from Steam under SERVER_TOKEN in order to appear on the server browser list. Fixes #155

2024-07-22 08:54 UTC, garrappachc requested changes

2024-07-22 08:54 UTC, garrappachc commented on packages/tf2-base/Dockerfile
> +ENV SEVER_TOKEN=""
Typo: `SERVER_TOKEN`

2024-07-22 21:00 UTC, joshuafhiggins commented on packages/tf2-base/Dockerfile
> +ENV SEVER_TOKEN=""
Fixed!

2024-07-24 06:48 UTC, garrappachc approved these changes

2024-07-24 06:49 UTC, merged

2024-07-24 08:58 UTC, garrappachc commented
Thanks!

2024-07-24 14:36 UTC, joshuafhiggins commented
You're welcome! On another note, would there be any interest in including some other environmental controls in tf2-base, like random crits, fixed shot patterns, and server tags? I think these would be very valuable for people to easily setup a server on their own with settings that are commonly changed. I'm willing to submit a PR for them, but obviously have the default values for them be what the default is now for the image as to not switch settings out from under people.

2024-07-24 15:24 UTC, garrappachc commented
> You're welcome! On another note, would there be any interest in including some other environmental controls in tf2-base, like random crits, fixed shot patterns, and server tags? I think these would be very valuable for people to easily setup a server on their own with settings that are commonly changed. I'm willing to submit a PR for them, but obviously have the default values for them be what the default is now for the image as to not switch settings out from under people.

These settings are a part of the `server.cfg` file, so they're easily accessible already; all one has to do is to provide their own `server.cfg.template` and reference env variables in it. Unless mounting the `server.cfg.template` is an issue, I don't see any value in doing this.

2024-07-24 17:50 UTC, joshuafhiggins commented
> These settings are a part of the `server.cfg` file, so they're easily accessible already; all one has to do is to provide their own `server.cfg.template` and reference env variables in it. Unless mounting the `server.cfg.template` is an issue, I don't see any value in doing this.

Ah I see, I didn't know you could mount a custom server.cfg.template, my bad!